# Generated by Django 5.1.5 on 2025-02-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='payment',
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment_invoice',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
